config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'site#home', as: :home
  resources :concerts, only: [:show, :new, :create] do
  	resources :comments, except: [:show]
  end

  post '/search', to: 'site#search'
  post 'concerts/popular', to: 'concerts#popular'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :concert
end

app/models/concert.rb
class Concert < ActiveRecord::Base
	has_many :comments
	validates_presence_of :artist, :venue, :city, :date, :price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@my_concert = Concert.find(params[:concert_id])
		@my_comments = @my_concert.comments
	end
	def create
		@my_concert = Concert.find(params[:concert_id])
		@my_comment = @my_concert.comments.new(comment_params)
		if @my_comment.save
			redirect_to concert_path(@my_concert)
		else
			render "new"
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:name, :comment)
	end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
	def new
		@my_concert = Concert.new
	end
	def create
		@my_concert = Concert.new(concert_params)
		if @my_concert.save
			redirect_to concert_path(@my_concert)
		else
			render "new"
		end
	end
	def show
		@my_concert = Concert.find_by(id:params[:id])
		@comments = @my_concert.comments.order(created_at: :desc)
		@my_comment = @my_concert.comments.new
		unless @my_concert
			render "no_concerts_found"
		end
	end
	def popular
		@concerts = Concert.all
 		@concerts = @concerts.sort_by do |concert|
 			concert.comments.count
 		end
 		@concerts = @concerts.last(10).reverse
	end

	private
	def concert_params
		params.require(:concert).permit(:artist, :venue, :city, :date, :price, :description)
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		@concerts = Concert.order(date: :asc).limit(10)
	end
	def search
		@my_price = params[:cost]
		@concerts = Concert.where("price < ?", @my_price)
		render "site/search"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/concerts/new.html.erb
<h1>Add a new concert</h1>

<% if @my_concert.errors.any? %>
	<ul>
		<% @my_concert.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for(@my_concert) do |f| %>
	<%= f.label :artist %>
	<%= f.text_field :artist %>
	<br><br>
	<%= f.label :venue %>
	<%= f.text_field :venue %>
	<br><br>
	<%= f.label :city %>
	<%= f.text_field :city %>
	<br><br>
	<%= f.label :date %>
	<%= f.datetime_local_field :date %>
	<br><br>
	<%= f.label :price %>
	<%= f.number_field :price %>
	<br><br>
	<%= f.label :description %>
	<%= f.text_area :description %>
	<br><br>
	<%= f.button %>
<% end %>

app/views/concerts/no_concerts_found.html.erb
<h1>No concerts found</h1>

app/views/concerts/popular.html.erb
<%= render "shared/concerts" %>

app/views/concerts/show.html.erb
<h1>Concert Details</h1>

<h2><%= @my_concert.artist %></h2>
<p><%= @my_concert.venue %></p>
<p><%= @my_concert.city %></p>
<p><%= @my_concert.date %></p>
<p>$ <%= @my_concert.price %></p>

<h3>Comments</h3>

<% count = 0 %>

<ul>
	<% @comments.each do |comment| %>
		<li>
			<b><%= comment.name %></b><br>
			<%= comment.comment %>
		</li>
		<% count = count + 1 %>
	<% end %>
</ul>

<% if count == 0 %>
	No comment yet. 
<% end %>

<h4>Leave your comment!</h4>

<%= form_for [@my_concert, @my_comment] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :comment %>
	<%= f.text_area :comment %>
	<br>
	<%= f.submit "Save" %>
<% end %>
  
<br>
<%= link_to 'Return to Home', home_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Concerts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_concerts.html.erb
<ul>
	<% @concerts.each do |concert| %>
		<% if concert.date.future? %>
			<li>
				<%= link_to concert.artist, concert_path(concert) %>
				<% if concert.description %>
					- 
				<% end %>
				<%= concert.description %>
				<%= concert.date %>
			</li>
		<% end %>
	<% end %>
</ul>

app/views/site/home.html.erb
<h1>Home</h1>

<h4>Filter by price</h4>

<%= form_tag('/search') do %>
	<%= label_tag 'Cost' %>
	<%= number_field_tag 'cost' %>
	<%= submit_tag 'Search' %>
<% end %>
<br>

<%= form_tag('concerts/popular') do %>
 	<b><%=label_tag 'Popular'%></b><br>
 	<%= submit_tag 'See Popular Concerts!' %>
<% end -%>

<h2>Happening Today:</h2>

<% count = 0 %>

<ul>
	<% @concerts.each do |concert| %>
		<% if concert.date.to_date == Date.today %>
			<li>
				<%= link_to concert.artist, concert_path(concert) %>
				<% if concert.description %>
					- 
				<% end %>
				<%= concert.description %>
				<%= concert.date %>
			</li>
			<% count = count + 1 %>
		<% end %>
	<% end %>
</ul>
<% if count == 0 %>
	No concerts registered for today :(
<% end %>

<h2>Happening Soon:</h2>

<%= render "shared/concerts" %>

<%= link_to "Create a new concert", new_concert_path %>

app/views/site/search.html.erb
<%= render "shared/concerts" %>